# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 11:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='data',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 11, 18, 11, 55, 11, 918388), null=True),
        ),
    ]
