# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budynek',
            name='administrator',
            field=models.ForeignKey(db_column='administrator', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.Pracownik'),
        ),
        migrations.AlterField(
            model_name='budynek',
            name='adres',
            field=models.ForeignKey(db_column='adresbudynek', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.AdresBudynek'),
        ),
        migrations.AlterField(
            model_name='faktura',
            name='wlasciciel',
            field=models.ForeignKey(blank=True, db_column='wlasciciel', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.Wlasciciel'),
        ),
        migrations.AlterField(
            model_name='faktura',
            name='wystawca',
            field=models.ForeignKey(db_column='wystawca', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.Wystawca'),
        ),
        migrations.AlterField(
            model_name='mieszkanie',
            name='budynek',
            field=models.ForeignKey(db_column='budynek', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.Budynek'),
        ),
        migrations.AlterField(
            model_name='nadgodziny',
            name='pracownik',
            field=models.ForeignKey(db_column='pracownik', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.Pracownik'),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='adres',
            field=models.ForeignKey(db_column='adres', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.Adres'),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='stanowisko',
            field=models.ForeignKey(db_column='stanowisko', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.Stanowisko'),
        ),
        migrations.AlterField(
            model_name='stanlicznik',
            name='mieszkanie',
            field=models.ForeignKey(db_column='mieszkanie', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.Mieszkanie'),
        ),
        migrations.AlterField(
            model_name='stanlicznik',
            name='typ',
            field=models.ForeignKey(db_column='typ', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.Licznik'),
        ),
        migrations.AlterField(
            model_name='wlasciciel',
            name='mieszkanie',
            field=models.ForeignKey(blank=True, db_column='mieszkanie', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.Mieszkanie'),
        ),
        migrations.AlterField(
            model_name='wydarzenie',
            name='budynek',
            field=models.ForeignKey(blank=True, db_column='budynek', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.Budynek'),
        ),
    ]
