# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_budynek_wydarzenia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='mieszkanie',
        ),
        migrations.AddField(
            model_name='ticket',
            name='mieszkaniec',
            field=models.ForeignKey(blank=True, db_column='mieszkaniec', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.Wlasciciel'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='kto',
            field=models.ForeignKey(blank=True, db_column='kto', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.Pracownik'),
        ),
    ]
