# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171118_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faktura',
            name='adres',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='data',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
