# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171107_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='kto',
            field=models.ForeignKey(blank=True, db_column='kto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.Pracownik'),
        ),
    ]
