# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20171108_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='mieszkaniec',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='kto',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
