# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171108_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='kto',
            field=models.TextField(default=None, null=True),
        ),
    ]
